-- Run once in the Supabase SQL Editor.
-- Bảng lưu trữ điểm số hoạt động học tập để tính bảng xếp hạng (Tuần, Ngày, Toàn thời gian).

create table if not exists public.leaderboard_scores (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  display_name text not null,
  avatar_url text,
  category text not null check (category in ('vocabulary', 'translation', 'sentence_order', 'game', 'mock_exam', 'streak')),
  points integer not null check (points > 0),
  description text,
  created_at timestamptz not null default now()
);

-- Chỉ mục tối ưu hóa truy vấn bảng xếp hạng theo thời gian và người dùng
create index if not exists leaderboard_scores_created_at_idx
  on public.leaderboard_scores (created_at desc);

create index if not exists leaderboard_scores_user_category_idx
  on public.leaderboard_scores (user_id, category, created_at desc);

-- Kích hoạt Row Level Security
alter table public.leaderboard_scores enable row level security;

-- Cho phép tất cả người dùng (authenticated & anon) đọc bảng điểm để hiển thị bảng xếp hạng công khai
drop policy if exists "Anyone can read leaderboard scores" on public.leaderboard_scores;
create policy "Anyone can read leaderboard scores"
  on public.leaderboard_scores for select
  to authenticated, anon
  using (true);

-- Cho phép người dùng đã đăng nhập ghi nhận điểm số của chính họ
drop policy if exists "Users can insert own score" on public.leaderboard_scores;
create policy "Users can insert own score"
  on public.leaderboard_scores for insert
  to authenticated
  with check (auth.uid() = user_id);
