-- Run this file in Supabase SQL Editor first.
-- Then import vocabulary.csv into public.vocabulary from Table Editor.

create table if not exists public.vocabulary (
  id bigint generated by default as identity primary key,
  book_level text not null,
  vocab text not null,
  english_meaning text,
  vietnamese_meaning text not null,
  word_type text,
  component text,
  created_at timestamptz not null default now()
);

create index if not exists vocabulary_book_level_idx
  on public.vocabulary (book_level);

alter table public.vocabulary enable row level security;

drop policy if exists "Public can read vocabulary" on public.vocabulary;

create policy "Public can read vocabulary"
on public.vocabulary
for select
using (true);
