-- Run once in Supabase SQL Editor to power the personal learning chart.
create table if not exists public.learning_activity (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  activity_type text not null check (activity_type in ('vocabulary_view', 'translation_answer')),
  vocabulary_id bigint references public.vocabulary(id) on delete set null,
  level text,
  lesson integer,
  question_index integer,
  is_correct boolean,
  occurred_at timestamptz not null default now()
);

create index if not exists learning_activity_user_date_idx
  on public.learning_activity (user_id, occurred_at desc);

alter table public.learning_activity enable row level security;
drop policy if exists "Users can read own learning activity" on public.learning_activity;
drop policy if exists "Users can add own learning activity" on public.learning_activity;
create policy "Users can read own learning activity" on public.learning_activity for select to authenticated using (auth.uid() = user_id);
create policy "Users can add own learning activity" on public.learning_activity for insert to authenticated with check (auth.uid() = user_id);
